
alias ll="ls -lh"
alias la="ls -A"
alias lla="ls -lA"
alias l="ls"
alias lh="ls -lhA"
alias lsa="ls -iablh"
alias psg="ps aux | grep "
alias sudo="sudo "
alias grep="grep --color=auto"
alias tmux="tmux -2"
alias bp="bpython"
alias rebash="source ~/.bashrc"
alias t="htt"
alias qt="git qt"
alias ls="ls -G --color=auto -X"
alias lsa="ls -iablhQ"
alias lsc="ls *.c -1"
alias lsh="ls -1 *.h"
alias psg="ps aux | grep "
alias _x="chmod +x"
alias :e="vim"
alias :q="exit"
alias cd..="cd .."
alias ..="cd .."