#!/bin/bash

shopt -s autocd




#
# Source git helpers if they're there.
#
test -f ~/scripts/git-completion.bash && source ~/scripts/git-completion.bash 





alias ls="ls --color=auto -X"
alias ll="ls -l"
alias la="ls -a"
alias lla="ls -la"

# When you feel desperate
alias lsa="ls -iablhQ"
alias lsc="ls *.c -1"
alias lsh="ls -1 *.h"
alias psg="ps aux | grep "

PATH=$PATH:/usr/local/texlive/2012/bin/x86_64-linux
PATH=$PATH:/opt/VirtualBox/
PATH=$PATH:/opt/arduino-0022/
PATH=$PATH:/opt/processing-1.5.1/
PATH="/usr/local/heroku/bin":$PATH
PATH=$PATH:/home/$(whoami)/scripts
PATH=$PATH:/home/$(whoami)/.cabal/bin
export PATH

function bprint {
  <$1 fold -w 72 | pr -F -o3 -h $1 | tee >( lpr )
}

function pprint {
  a2ps -R -T4 --columns=1 --borders=off --header="" --left-footer="" --right-footer="" --line-numbers=1 -f 10 --pro=color -o out.ps $1
  echo "File in out.ps"
}