#!/bin/bash

cat - \
 | sed -e "s/ cc /\n cc /g" \
 | sed -e "s/\( -[a-zA-Z]\)/\n    \1/g" \
 | hilite.sh -r "^make\[.*\]:.*" -f black -B \
 | hilite.sh -r "^.*[Ww]arning[: ].*" -f yellow -B \
 | hilite.sh -r "^.*[Ee]rror[: ].*" -f red -B \
 | less -r

