#!/bin/bash


#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  random:"
  echo "    Get a random todo from the list"
  echo ""
  exit
}

<$TODO_DIR/todo.txt awk '{printf "%02d %s\n", NR, $0}' | shuf -n 1
